# Generated by Django 5.1.3 on 2024-11-14 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('Address', models.CharField(max_length=100)),
                ('Depid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.department')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('Address', models.CharField(max_length=100)),
                ('Qualification', models.CharField(max_length=100)),
                ('Depid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.department')),
                ('Tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
